services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ..:/app
    environment:
      COMPOSER_ALLOW_SUPERUSER: "1"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ..:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    env_file: ./../.env
    volumes:
      - ./postgres/backup:/backup
      - ${POSTGRES_PATH}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  pgdata:
    driver: local
